# Generated by Django 4.0.4 on 2022-05-30 22:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memes_api', '0002_memenopic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MemeNoPic',
            new_name='MemeNoImg',
        ),
    ]
